name: Build and Test with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build  

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=Techdome-frontend \
            -Dsonar.organization=TRIGENT \
            -Dsonar.host.url=http://13.201.8.107:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.sources=.
